name: VRChat
main: base.plugin.ChatHandler
version: 1.2.8
commands:
    vrchat:
        description: Generic VRChat command.
    ooc:
        description: Changes chat to the global (out-of-character) chat channel
    say:
        description: Changes chat to the local (8 blocks) chat channel
    global:
        description: Changes chat to the local (1000000 blocks) chat channel
    emote:
        description: Sends a local emote
    s:
        description: Alias for say
    gl:
        description: Alias for global
    e:
        description: Alias for emote
